New Poisson RNG
adamrher/CAM pull request #3
Opened 2021-10-04 20:22 UTC by jkreschke

Implemented a new Poisson RNG not using the direct method, so runs efficiently for all lambda.

2021-10-04 20:26 UTC, jkreschke commented
Will @rls347, @mchinita 
please review this PR, thanks!

2021-10-05 16:19 UTC, mchinita commented
Hi Everyone, 

I think there is a typo in L1063: alphinv = 1.1239_r8 + **1.328**_r8/(b - 3.4_r8)

I think the number is 1.1328. It's just missing "1" before "328". Do you agree?

2021-10-05 16:33 UTC, jkreschke commented
Hi Maria,

Yes, you are correct. Thanks for double checking the paper!

Jake


> On Oct 5, 2021, at 9:19 AM, mchinita ***@***.***> wrote:
> 
> 
> Hi Everyone,
> 
> I think there is a typo in L1063: alphinv = 1.1239_r8 + 1.328_r8/(b - 3.4_r8)
> 
> I think the number is 1.1328. It's just missing "1" before "328". Do you agree?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/adamrher/CAM/pull/3#issuecomment-934559429>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVY4G5S2GZMWRDCJRJ56ACLUFMQQ5ANCNFSM5FKF6VQA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-10-05 16:44 UTC, mchinita commented
Hi Jake,

Sure! 

One genuine question: our lambdas are usually smaller than 10 (e.g. delta_Z/L0 = 150/100 = 1.5). Do you think this algorithm works as well as it does for lambdas > 10? If I understand correctly, the values in Table 1 were optimized for lambdas >= 10. 

Thanks for coding the new algorithm! I should probably integrate it in SHOC_MF as well, but I will let you know before. 

Maria

2021-10-05 16:47 UTC, mikaelwitte requested changes
In the preamble, state which algorithm you use from the Hormann reference (PTRS, right?)

Line 1063: Agreed with Maria, second constant in alphinv should be 1.1328_r8. 

Line 1070: The final constant here is given as 0.445 in the Hormann paper. Just checking whether this was intentional.

Everything else looks good, thanks Jake!

2021-10-05 17:16 UTC, jkreschke commented
Hi everyone,

Thanks for looking for over the code and sorry for the confusion, I should have specified that the PTRS algorithm is being used. 

I didn’t actually try testing the algorithm for lambda < 10 to see what happens. The Knuth algorithm is inexpensive for small lambda so we just use it in that case.

The k value differs between the two algorithms presented in Hormann (for reasons unknown to me). In the first algorithm the constant is 0.445 but in the PTRS version it is 0.43.

Best,
Jake

> On Oct 5, 2021, at 9:47 AM, Mikael ***@***.***> wrote:
> 
> 
> @mikaelwitte requested changes on this pull request.
> 
> In the preamble, state which algorithm you use from the Hormann reference (PTRS, right?)
> 
> Line 1063: Agreed with Maria, second constant in alphinv should be 1.1328_r8.
> 
> Line 1070: The final constant here is given as 0.445 in the Hormann paper. Just checking whether this was intentional.
> 
> Everything else looks good, thanks Jake!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/adamrher/CAM/pull/3#pullrequestreview-771699926>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVY4G5RFZR5NNMTM52OQPV3UFMT3DANCNFSM5FKF6VQA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-10-05 17:41 UTC, mchinita commented
Indeed Jake. I forgot for a second that smaller values of L0 and thus bigger lambdas were the reason for this new algorithm. If I remember correctly (Adam correct me if I'm wrong), Sc are better captured using very small L0 with the old entrainment formulation. But with the new TKE enhanced entrainment formulation, we are able to properly represent Sc while keep using the L0 = a*sqrt(ztop) which produces larger L0 values, and thus smaller lambdas. So yes, in that case, we can still use the old algorithm.

Thanks!
Maria

2021-10-05 21:25 UTC, adamrher approved these changes
Looks good. I will approve assuming you address my comments.

2021-10-05 21:25 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +       if (lambda < 10) then
Jake can you change this to 10._r8 to make it compiler proof?

2021-10-05 21:25 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +  ! Implements PTRS algorithm from W. Hormann
What does PTRS stand for? If it's not too long, I'd like to see the unabbreviated version here.

2021-10-05 21:25 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +         if (k <= 0 .or. (us < 0.013_r8 .and. V(1,1) > us)) then
similarly change this to k <= 0._r8

2021-10-05 21:25 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +         if (k < 10) then
same here

2021-10-05 21:30 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +         if (k < 10) then
I also take this back! k is an integer.

2021-10-05 21:30 UTC, adamrher commented on src/physics/cam/clubb_mf.F90
> +         if (k <= 0 .or. (us < 0.013_r8 .and. V(1,1) > us)) then
oh wait, I take this back. k is an integer.

2021-10-05 21:46 UTC, jkreschke commented
Done!

> On Oct 5, 2021, at 2:26 PM, Adam Herrington ***@***.***> wrote:
> 
> 
> @adamrher approved this pull request.
> 
> Looks good. I will approve assuming you address my comments.
> 
> In src/physics/cam/clubb_mf.F90 <https://github.com/adamrher/CAM/pull/3#discussion_r722716221>:
> 
> >           enddo
>         enddo
>  
>    end subroutine poisson
>  
> +  subroutine whichRNG(kiss_gen,lambda,kout)
> +  !**********************************************************************
> +  ! Interface for the two poisson rng subroutines
> +  ! chooses the appropriate subroutine based on the value of lambda
> +  !**********************************************************************
> +   use shr_RandNum_mod, only: ShrKissRandGen
> +
> +       type(ShrKissRandGen), intent(inout) :: kiss_gen
> +       real(r8),             intent(in)    :: lambda
> +       integer,              intent(out)   :: kout
> +
> +       if (lambda < 10) then
> Jake can you change this to 10._r8 to make it compiler proof?
> 
> In src/physics/cam/clubb_mf.F90 <https://github.com/adamrher/CAM/pull/3#discussion_r722716686>:
> 
> > @@ -1027,6 +1040,59 @@ subroutine knuth(kiss_gen,lambda,kout)
>  
>    end subroutine knuth
>  
> +  subroutine hormann(kiss_gen,lambda,kout)
> +  !**********************************************************************
> +  ! Discrete random poisson
> +  ! Implements PTRS algorithm from W. Hormann
> What does PTRS stand for? If it's not too long, I'd like to see the unabbreviated version here.
> 
> In src/physics/cam/clubb_mf.F90 <https://github.com/adamrher/CAM/pull/3#discussion_r722717654>:
> 
> > +      b = 0.931_r8 + 2.53_r8*sqrt(lambda)
> +      a = -0.059_r8 + 0.02483_r8*b
> +      vr = 0.9277_r8 - 3.6224_r8/(b - 2._r8)
> +      alphinv = 1.1239_r8 + 1.1328_r8/(b - 3.4_r8)
> +
> +      do
> +         call kiss_gen%random(U)
> +         call kiss_gen%random(V)
> +         U(1,1) = U(1,1) - 0.5_r8
> +         us = 0.5_r8 - abs(U(1,1))
> +         k = floor( (2._r8*a/us + b)*U(1,1) + lambda + 0.43_r8 )
> +         if (us >= 0.07_r8 .and.  V(1,1) <= vr) then
> +            kout = k
> +            exit
> +         end if
> +         if (k <= 0 .or. (us < 0.013_r8 .and. V(1,1) > us)) then
> similarly change this to k <= 0._r8
> 
> In src/physics/cam/clubb_mf.F90 <https://github.com/adamrher/CAM/pull/3#discussion_r722717862>:
> 
> > +
> +      do
> +         call kiss_gen%random(U)
> +         call kiss_gen%random(V)
> +         U(1,1) = U(1,1) - 0.5_r8
> +         us = 0.5_r8 - abs(U(1,1))
> +         k = floor( (2._r8*a/us + b)*U(1,1) + lambda + 0.43_r8 )
> +         if (us >= 0.07_r8 .and.  V(1,1) <= vr) then
> +            kout = k
> +            exit
> +         end if
> +         if (k <= 0 .or. (us < 0.013_r8 .and. V(1,1) > us)) then
> +            cycle
> +         end if
> +         ! compute log(k!). If k >=10 use stirling's approximation
> +         if (k < 10) then
> same here
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/adamrher/CAM/pull/3#pullrequestreview-771996857>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVY4G5TGHUDGZICYZVK2EBTUFNUO5ANCNFSM5FKF6VQA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-10-05 21:52 UTC, merged